#!/bin/bash

rp='([0-9]+): (starting|finished) install of package ([^:]+)(:[^ ]+) \(([0-9]+ of [0-9]+).( ([0-9]+) failed\)|)'
rt='[0-9]+: (starting|finished) install of targets (.*)'

# colors
default='\e[0m'
grey='\e[90m'
red='\e[1;31m'

# read last 500 lines (overkill, but we potentially have to skip a lot of fetch lines)
tail -F -n500 /var/log/paludis.log \
    | egrep --line-buffered '(starting|finished) install' \
    | while read line; do
        if [[ ${line} =~ ${rt} ]]; then
            state=${BASH_REMATCH[1]}
            targets=${BASH_REMATCH[2]}
            [[ -n ${failed} ]] && echo ""
            echo -e "${grey}${state} install of:${default} ${targets}"
            unset failed
        elif [[ ${line} =~ ${rp} ]]; then
            date=${BASH_REMATCH[1]}
            state=${BASH_REMATCH[2]}
            pkg=${BASH_REMATCH[3]}
            slotrepo=${BASH_REMATCH[4]}
            outof=${BASH_REMATCH[5]}
            lastfailed=${BASH_REMATCH[7]:-0}
            # if ${failed} is unset we are in the first iteration
            if [[ -n ${failed} ]]; then
                if [[ ${failed} -ne ${lastfailed} ]]; then
                    echo -e " ${red}failed!${default}"
                else
                    echo ""
                fi
            fi
            failed=${lastfailed}
            echo -n -e "${grey}$(date --date=@${date} '+%F %T') ${state}${default} ${pkg}${grey}${slotrepo}${default} [${outof}]"
        else
            echo "UNHANDLED LINE: ${line}"
        fi
    done
