#!/bin/bash

dirs=()

if [[ -d .git ]] ; then
	dirs=( . )
else
	for dir in * ; do
		[[ -d "${dir}"/.git ]] || continue
		dirs+=( "${dir}" )
	done
fi

for dir in "${dirs[@]}" ; do
	cd "${dir}"

	list=( $(git status --porcelain --untracked-files=all | sed -e 's#^.. ##g') )

	for line in "${list[@]}" ; do
		c='*' ; p='*'

		if [[ "${line}" =~ ^packages/([A-Za-z0-9+_.-]+)/([A-Za-z0-9+_.-]+)/([A-Za-z0-9+_.-]+)\.exlib$ ]] ; then
			c=${BASH_REMATCH[1]}
			[[ ${BASH_REMATCH[2]} != exlibs ]] && p=${BASH_REMATCH[2]}
			exlib=${BASH_REMATCH[3]}
		elif [[ "${line}" =~ ^exlibs/([A-Za-z0-9+_.-]+)\.exlib$ ]] ; then
			exlib=${BASH_REMATCH[1]}
		else
			continue
		fi

		git add "${line}"

		for pkg in $(cave print-ids -s install -m "${c}/${p}[.INHERITED<${exlib}]" -f 'packages/%c/%p/%p-%v.exheres-0\n') ; do
			[[ -e "${pkg}" ]] && list+=( "${pkg}" )
		done
	done

	for line in "${list[@]}" ; do
		if [[ "${line}" =~ ^(packages/[A-Za-z0-9+_.-]+/[A-Za-z0-9+_.-]+/[A-Za-z0-9+_.-]+)\.exheres-0$ ]] ; then
			base=${BASH_REMATCH[1]}

			if [[ "$base" =~ -scm$ ]] ; then
				newbase=${base}
			elif [[ "$base" =~ ^(.*-r)([[:digit:]]+)$ ]] ; then
				newbase="${BASH_REMATCH[1]}$((BASH_REMATCH[2] + 1))";
			else
				newbase="${base}-r1"
			fi

			[[ ${base} != ${newbase} ]] && git mv "${base}".exheres-0 "${newbase}".exheres-0
			git add "${newbase}".exheres-0
		fi
	done

	if [[ $# -ge 1 ]] ; then
		git commit -m "$1"
	fi

	cd ..
done
